/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    ImageUploader: typeof import('./components/ImageUploader.vue')['default']
    LoginForm: typeof import('./components/LoginForm.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    PredictionDashboard: typeof import('./components/PredictionDashboard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignupForm: typeof import('./components/SignupForm.vue')['default']
  }
}
